#!/usr/bin/env bash

HOSTN=${HOSTNAME//[0-9]/}

ROCM_VERSION=$1
if [ $# -lt 1 ]; then
    echo "Usage: source scripts/setup-rocm.sh <ROCm version>"
    return 1
fi

# Developer knobs.
MNEME_ENABLE_TESTS=${MNEME_ENABLE_TESTS:-Off}
MNEME_ENABLE_LOGGER=${MNEME_ENABLE_LOGGER:-Off}
MNEME_ENABLE_PYTHON=${MNEME_ENABLE_PYTHON:-Off}
MNEME_LINK_SHARED_LLVM=${MNEME_LINK_SHARED_LLVM:-Off}

ml load cmake/3.23.1
ml load rocm/${ROCM_VERSION}

LLVM_INSTALL_DIR=${ROCM_PATH}/llvm
PROTEUS_DIR=${PROTEUS_DIR:-../proteus/install-${HOSTN}-rocm-${ROCM_VERSION}}

mkdir -p build-${HOSTN}-rocm-${ROCM_VERSION}
pushd build-${HOSTN}-rocm-${ROCM_VERSION}

cmake .. \
-DLLVM_INSTALL_DIR=${LLVM_INSTALL_DIR} \
-DCMAKE_PREFIX_PATH=${PROTEUS_DIR} \
-Dproteus_DIR=${PROTEUS_DIR} \
-DCMAKE_C_COMPILER=${LLVM_INSTALL_DIR}/bin/amdclang \
-DCMAKE_CXX_COMPILER=${LLVM_INSTALL_DIR}/bin/amdclang++ \
-DMNEME_ENABLE_HIP=on \
-DMNEME_ENABLE_CUDA=off \
-DMNEME_ENABLE_TESTS=On \
-DMNEME_ENABLE_LOGGER=${MNEME_ENABLE_LOGGER} \
-DMNEME_ENABLE_PYTHON=${MNEME_ENABLE_PYTHON} \
-DMNEME_LINK_SHARED_LLVM=${MNEME_LINK_SHARED_LLVM} \
-DCMAKE_INSTALL_PREFIX=../install-${HOSTN}-rocm-${ROCM_VERSION} \
-DCMAKE_EXPORT_COMPILE_COMMANDS=on \
"${@:2}"

popd
